version: "3"

services:
  app:
    build:
      context: .
    environment:
      PYTHONUNBUFFERED: True
      SUPABASE_URL: http://localhost:8000
      SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    command: ["uvicorn", "dna.api.external_api:app", "--host", "0.0.0.0", "--port", "9000", "--reload"]
    depends_on:
      - rabbitmq
      - flower
      - worker
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:9000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  flower:
    image: mher/flower
    volumes:
      - .:/app
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitmq

  worker:
    build: .
    command: [
      "celery",
      "--workdir", "/app",
      "-A", "dna",
      "--config", "dna.tasks.celery_config",
      "worker", "-E",
      "-Q", "celery",
      "-O", "fair",
      "--loglevel=info"
    ]
    volumes:
      - .:/app
    environment:
      C_FORCE_ROOT: "1"
    depends_on:
      - rabbitmq
